### PR TITLE
update for python 3.7 and 3.8

### PR DESCRIPTION
**Pull request by ddurham2**

### CODE REVIEW

**Comment by ddurham2** [comment]
I couldn't get the unit tests to run.  Tips?

**Comment by ddurham2** [comment]
The check that failed is due to it running under python3.3 and support for that has been dropped.  Can't fix.

**Comment by yohm** [comment]
@saghul Could you check this pretty nice PR by @ddurham2 ?

**Comment by saghul** [comment]
PR looks good, we just need to drop old Python versions and tests will pass. I'll try to do it when I get some time, but if you feel like sending a PR that would be welcome too.

**Comment by yohm** [comment]
@ddurham2  With #22 , this PR should pass CIs.
Please pull (or rebase) the latest master branch and see if it passes the tests.
It would be great if you add tests with Python 3.7 and 3.8 as well. The settings are already included in .travis.yml and appveyor.yml files as comments. Uncomment these to run the tests on these Python versions.

**Comment by ddurham2** [comment]
So 3.7 passed, but 3.8 did on the CI.   nosetest -v succeeded on _my_ local system for both 3.7 and 3.8.  So I don't think there's anything wrong with the module itself, but something wrong in the travis environment.

Is that something you can fix?  I'm guessing this is the first time 3.8 has been attempted.

**Comment by saghul** [comment]
This is the error:

```
Traceback (most recent call last):
  File "..\fibers\__init__.py", line 5, in <module>
    from fibers._cfibers import *
ImportError: DLL load failed while importing _cfibers: The parameter is incorrect.
```

Weird, maybe CFFI related. Let's comment out Python 3.8 on Windows and land this, it can be fixed later.

Thanks!

**Comment by ddurham2** [comment]
w00t!

**Comment by ddurham2** [comment]
can we merge?

**Comment by ddurham2** [comment]
@saghul, thankya kindly!

**Comment by ddurham2** [comment]
Any possibility of making a release, and publish to pypi?  Can I assist?

**Comment by saghul** [comment]
I'll try to get to it soon, running short of time these days alas.

**Comment by ddurham2** [comment]
Any possibility of pushing to pypi?  (Version 1.1.0 in __init__.py needs a bump probably to 1.2.0)

**Comment by ddurham2** [comment]
Any possibility of pushing to pypi? (Version 1.1.0 in init.py needs a bump probably to 1.2.0)

**Pull request merged**
